// Re-export from domain-split prompt modules
export {
  buildDomainExpertise,
  WRITING_SECTION_PROMPTS,
  resolveSectionPrompt,
  buildWriterSystemPrompt,
  buildVerifierSystemPrompt,
  buildVerifierPrompt,
  buildRefinerSystemPrompt,
  buildRefinerPrompt,
  buildOutlinePrompt,
  buildBlueprintPrompt,
  buildAnalysisPrompt,
  TRANSLATE_SYSTEM_PROMPT,
  buildTranslateUserPrompt,
  KNOWLEDGE_ANALYZE_SYSTEM,
  buildFullAnalysisPrompt,
  buildChunkAnalysisPrompt,
  buildConsistencyPrompt,
  buildEvaluationContractPrompt,
  buildDimensionPromptV2,
  buildPaperCandidatesPromptV2,
  buildSynthesisPrompt,
  buildAssetSummary,
  buildRoadmapPrompt,
} from "./prompts/index";
